// ui/islands/timeline/historical-events.ts — statische Referenztabelle historischer
// Ereignisse im deutschsprachigen Raum (Spec 20 §1.10 [S] "historische Ereignisse als
// Kontext"). Reine Daten, keine Logik — 1:1 aus dem Orakel `legacy-v8/timeline-hist-events.js`
// (`_HIST_EVENTS`) übernommen (Auftrag: "reine Referenzdaten, 1:1 als TypeScript-Konstante
// übernehmbar"). Kategorien wörtlich wie im Orakel: war/disease/political/religion/natural.
export type HistEventCategory = 'war' | 'disease' | 'political' | 'religion' | 'natural';

export interface HistEvent {
  year: number;
  label: string;
  cat: HistEventCategory;
}

export const HIST_EVENTS: readonly HistEvent[] = [
  { year: 1315, label: 'Große Hungersnot in Europa', cat: 'natural' },
  { year: 1347, label: 'Schwarzer Tod — Pest erreicht Europa', cat: 'disease' },
  { year: 1356, label: 'Goldene Bulle (Reichsverfassung)', cat: 'political' },
  { year: 1386, label: 'Gründung Universität Heidelberg', cat: 'political' },
  { year: 1431, label: "Verbrennung Jeanne d'Arc", cat: 'political' },
  { year: 1450, label: 'Gutenberg-Bibel — Buchdruck', cat: 'political' },
  { year: 1492, label: 'Columbus erreicht Amerika', cat: 'political' },
  { year: 1517, label: 'Luthers Thesenanschlag — Reformation', cat: 'religion' },
  { year: 1524, label: 'Bauernkrieg in Deutschland', cat: 'war' },
  { year: 1555, label: 'Augsburger Religionsfriede', cat: 'religion' },
  { year: 1572, label: 'Bartholomäusnacht (Frankreich)', cat: 'war' },
  { year: 1618, label: 'Dreißigjähriger Krieg beginnt', cat: 'war' },
  { year: 1633, label: 'Pest in München (ca. 7000 Tote)', cat: 'disease' },
  { year: 1648, label: 'Westfälischer Friede — Ende 30j. Krieg', cat: 'war' },
  { year: 1683, label: 'Türkenbelagerung Wiens', cat: 'war' },
  { year: 1700, label: 'Großer Nordischer Krieg beginnt', cat: 'war' },
  { year: 1709, label: 'Große Hungersnot in Zentraleuropa', cat: 'natural' },
  { year: 1740, label: 'Österreichischer Erbfolgekrieg', cat: 'war' },
  { year: 1756, label: 'Siebenjähriger Krieg', cat: 'war' },
  { year: 1763, label: 'Hubertusburger Friede', cat: 'war' },
  { year: 1789, label: 'Französische Revolution', cat: 'political' },
  { year: 1796, label: 'Napoleon in Italien — Feldzüge beginnen', cat: 'war' },
  { year: 1803, label: 'Reichsdeputationshauptschluss', cat: 'political' },
  { year: 1806, label: 'Ende des Heiligen Röm. Reiches', cat: 'political' },
  { year: 1813, label: 'Völkerschlacht bei Leipzig', cat: 'war' },
  { year: 1815, label: 'Wiener Kongress — Neuordnung Europas', cat: 'political' },
  { year: 1830, label: 'Julirevolution in Frankreich', cat: 'political' },
  { year: 1832, label: 'Hambacher Fest — Demokratiebewegung', cat: 'political' },
  { year: 1845, label: 'Irische Hungersnot — Massenemigration', cat: 'natural' },
  { year: 1848, label: 'Märzrevolution in Deutschland', cat: 'political' },
  { year: 1849, label: 'Niederschlagung der Revolution', cat: 'political' },
  { year: 1854, label: 'Krimkrieg', cat: 'war' },
  { year: 1866, label: 'Deutschen Krieg (Preußen–Österreich)', cat: 'war' },
  { year: 1870, label: 'Deutsch-Französischer Krieg', cat: 'war' },
  { year: 1871, label: 'Gründung Deutsches Reich', cat: 'political' },
  { year: 1873, label: 'Gründerkrach — Wirtschaftskrise', cat: 'political' },
  { year: 1878, label: 'Sozialistengesetz (Bismarck)', cat: 'political' },
  { year: 1888, label: 'Dreikaiserjahr — Wilhelm II. Kaiser', cat: 'political' },
  { year: 1890, label: 'Bismarck entlassen', cat: 'political' },
  { year: 1900, label: 'Boxer-Aufstand · Weltausstellung Paris', cat: 'political' },
  { year: 1905, label: 'Erstes Marokko-Krieg / Algeciraskonferenz', cat: 'war' },
  { year: 1914, label: 'Erster Weltkrieg beginnt', cat: 'war' },
  { year: 1916, label: 'Verdun · Somme — Massensterben', cat: 'war' },
  { year: 1917, label: 'Russische Revolution', cat: 'political' },
  { year: 1918, label: 'Ende WWI · Spanische Grippe', cat: 'disease' },
  { year: 1919, label: 'Weimarer Republik · Versailler Vertrag', cat: 'political' },
  { year: 1923, label: 'Hyperinflation in Deutschland', cat: 'political' },
  { year: 1929, label: 'Weltwirtschaftskrise', cat: 'political' },
  { year: 1933, label: 'NS-Machtübernahme', cat: 'political' },
  { year: 1935, label: 'Nürnberger Gesetze', cat: 'political' },
  { year: 1938, label: 'Anschluss Österreichs · Kristallnacht', cat: 'political' },
  { year: 1939, label: 'Zweiter Weltkrieg beginnt', cat: 'war' },
  { year: 1942, label: 'Wannseekonferenz · Holocaust', cat: 'war' },
  { year: 1943, label: 'Stalingrad — Wendepunkt', cat: 'war' },
  { year: 1945, label: 'Ende Zweiter Weltkrieg', cat: 'war' },
  { year: 1948, label: 'Berliner Blockade · Währungsreform', cat: 'political' },
  { year: 1949, label: 'Gründung BRD und DDR', cat: 'political' },
  { year: 1953, label: 'Volksaufstand DDR', cat: 'political' },
  { year: 1957, label: 'Römische Verträge — EWG gegründet', cat: 'political' },
  { year: 1961, label: 'Mauerbau Berlin', cat: 'political' },
  { year: 1968, label: 'Prager Frühling · Studentenbewegung', cat: 'political' },
  { year: 1972, label: 'Olympia München — Terroranschlag', cat: 'political' },
  { year: 1986, label: 'Tschernobyl-Reaktorunfall', cat: 'natural' },
  { year: 1989, label: 'Mauerfall Berlin', cat: 'political' },
  { year: 1990, label: 'Deutsche Wiedervereinigung', cat: 'political' },
  { year: 1993, label: 'Maastricht-Vertrag — EU gegründet', cat: 'political' },
  { year: 2002, label: 'Euro-Bargeld eingeführt', cat: 'political' },
  { year: 2004, label: 'EU-Erweiterung auf 25 Mitglieder', cat: 'political' },
  { year: 2005, label: 'Merkel erste Bundeskanzlerin', cat: 'political' },
  { year: 2008, label: 'Weltfinanzkrise', cat: 'political' },
  { year: 2009, label: 'Lissabon-Vertrag in Kraft', cat: 'political' },
  { year: 2011, label: 'Fukushima-Reaktorunfall', cat: 'natural' },
  { year: 2015, label: 'Flüchtlingskrise in Europa', cat: 'political' },
  { year: 2016, label: 'Brexit-Referendum', cat: 'political' },
  { year: 2020, label: 'COVID-19-Pandemie', cat: 'disease' },
  { year: 2022, label: 'Russischer Angriffskrieg auf Ukraine', cat: 'war' },
  { year: 2024, label: 'Europawahl — Rechtsruck in Europa', cat: 'political' },
];
